---
- name: int servo deplo
  hosts: intService

  tasks:
    - name: check that docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
        become: true

    - name: Ensure docker deamon is running
      service:
        name: docker
        state: started
      become: true

    - name: export image
        shell: "docker save intservice:latest > /tmp/intservice.tar"
        become: yes
        delegate_to: 127.0.0.1

    - name: set permissions
        file:
          path: /tmp/intservice.tar
          owner: ubuntu
          group: ubuntu
          mode: '0777'
        become: yes
        delegate_to: 127.0.0.1

    - name: Copy Docker image to remote location
        copy:
          src: /tmp/intservice.tar
          dest: /tmp/intservice.tar

    - name: Load Docker image
        docker_image:
          name: intservice
          tag: latest
          load_path: /tmp/intservice.tar
        become: yes
