---
- name: int servo deplo
  hosts: KoJoey
  become: true

  tasks:
    - name: check that docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start  docker service
      service:
        name: docker
        state: started

    - name: Start weatherapi container
      shell: "docker run joey/weatherapi:{{ tag }} -c 'israel' "
