---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: intjoey2020
    instance_type: t2.micro
    security_group: Sec_Group
    image: i-02cb2631bbb3418a4
    region: us-east-2
  tasks:
    - name: Launch instance
      amazon.aws.ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes
      register: ec2