- name: Start sandbox instances
  hosts: localhost
  gather_facts: false
  vars:
    instance_ids:
      - 'i-02cb2631bbb3418a4'
      - 'i-0598730321f470405'
      - 'i-00b63e1d689f716e8'
    region: us-east-2
  tasks:
    - name: Start the sandbox instances
      amazon.aws.ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: vpc-6d5be406
        assign_public_ip: yes


# Start stopped instances specified by tag
#
#- amazon.aws.ec2:
#    instance_tags:
#      Name: ExtraPower
#    state: running
